### ISSUE TITLE
Context headers not being passed

### ISSUE THREAD

**Issue by rafbgarcia** [bytewitchcraft/apollo-absinthe-upload-link#12]
When I make a request with a file, it goes to the `createUploadMiddleware`, and I don't have my `authentication` header on that request.

In the image below: the 1st request has the authentication token, the second one, being the one with the file, doesn't.

<img width="1126" alt="screen shot 2018-08-21 at 11 59 36 am" src="https://user-images.githubusercontent.com/1904314/44410018-e2b48380-a539-11e8-9868-ebcf985c5456.png">

Related code

```ts
  apolloLink() {
    return this.authContext()
      .concat(createUploadMiddleware({ uri: ENV.apiHost }))
      .concat(this.httpLink.create({ uri: ENV.apiHost }))
  }

  authContext = () => (
    setContext(async (_operation, _prevContext) => {
      const {token} = await this.customer.current()
      let headers = new HttpHeaders()
      if (token) {
        headers = headers.set('authorization', `Bearer ${token}`)
        return { headers }
      }
      return {}
    })
  )
```

I cloned the repo and saw the tests, they look fine, however this is happening.

Any clue why?

**Comment by juddey** [comment]
I'm seeing disappearing headers under this scenario too. Not sure why, but if I find out I'll repost back here.

**Comment by juddey** [comment]
It wasn't my headers disappearing, I just hadn't implemented the `x-requested-with` header: 

https://github.com/bytewitchcraft/apollo-absinthe-upload-link/pull/2#issuecomment-364216224

**Comment by ihorkatkov** [comment]
@rafbgarcia Hey. Do you still have that issue?
I think that you may have it because of `setContext` or the way how you combine links. Can you provide with a sample repo?

**Comment by rafbgarcia** [comment]
Hey @ihorkatkov, I don't have that issue anymore, thanks.
