### ISSUE TITLE
introduce customizable fetch 

### ISSUE THREAD

**Issue by krystofbe** [bytewitchcraft/apollo-absinthe-upload-link#13]
hi @ihorkatkov!

Would you review and merge https://github.com/bytewitchcraft/apollo-absinthe-upload-link/pull/10?

This gives others the possibility to provide a customized fetch function

**Comment by ihorkatkov** [comment]
Hi. Merged. Thanks for the contribution :+1:

**Comment by krystofbe** [comment]
❤️
