### ISSUE TITLE
Mutation's context.fetchOptions not being added to actual fetch event.

### ISSUE THREAD

**Issue by baleeds** [bytewitchcraft/apollo-absinthe-upload-link#16]
In trying to add progress bars to file uploads, I was led to [this comment](https://github.com/jaydenseric/apollo-upload-client/issues/88#issuecomment-434907278), where a solution is proposed that uses a fetch wrapper for xhr to provide hooks for progress events.
```
  const httpLink = createUploadLink({
    uri: API_URL,
    fetch: buildAxiosFetch(axios, (config, input, init) => ({
      ...config,
      onUploadProgress: init.onUploadProgress,
    })),
  });
```
These hooks fire an event that is added to the fetch options, called `onUploadProgress`.
```
apolloClient.mutate({
  mutation: UPLOAD_FILE,
  variables: { file },
  context: {
    fetchOptions: {
      onUploadProgress: (progress => {
        console.info(progress);
      }),
    }
  },
});
```
The problem is that in apollo-absinthe-upload-link, the context.fetchOptions from a mutation are not being added to the fetch.

**Comment by ihorkatkov** [comment]
Hey. Thanks for the issue and PR. I merged it. Unfortunately, I am in vacation and my laptop is broken, so I will publish the library to NPM as soon as I repair my laptop

**Comment by juddey** [comment]
Thanks for the fix, just discoverted this today :)
