### ISSUE TITLE
Update NPM Package with Latest Changes

### ISSUE THREAD

**Issue by andreragsilva** [bytewitchcraft/apollo-absinthe-upload-link#27]
Hey @bytewitchcraft 🤙 

Could you please update the NPM package? 

We would really appreciate it since most requests that send a file require authentication...

Thanks!

**Comment by ihorkatkov** [comment]
Hey @rageofflames,

I thought I published it :sweat_smile: 

Thanks for the reminder, I will publish it ASAP
