### ISSUE TITLE
Babel loader issue?

### ISSUE THREAD

**Issue by gbxl** [bytewitchcraft/apollo-absinthe-upload-link#5]
Hey, 

Thanks so much for the recent updates, great work 👍 

I can't run the newest version with my project though. This might be an issue on my side (still debugging this), but I think it comes from the module:

```
ERROR in ./~/apollo-absinthe-upload-link/src/index.js
Module parse failed: .../node_modules/apollo-absinthe-upload-link/src/index.js Unexpected token (24:21)
You may need an appropriate loader to handle this file type.
|           uri,
|           body: formData,
|           headers: { ...contextHeaders, ...headers },
|         })
|       }
 @ ./src/apollo-client.js 15:32-70
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:5000 ./src/index.js
```

I exclude the node_modules in my own babel/webpack loading logic so i don't think it comes from my setup.

Cheers

**Comment by ihorkatkov** [comment]
Hey @gbxl .
It is project issue. As workaround for now, you can transpile it via webpack/babel. During this week I fix it. Thanks

**Comment by ihorkatkov** [comment]
@gbxl I have already published the fix. Please try

**Comment by gbxl** [comment]
Excellent! Thank you so much!
